"""
This type stub file was generated by pyright.
"""

def force_float(elt): # -> float:
    ...

def build_options_url(ticker, date=...):
    """Constructs the URL pointing to options chain"""
    ...

def get_options_chain(ticker, date=..., raw=..., headers=...): # -> dict[str, DataFrame]:
    """Extracts call / put option tables for input ticker and expiration date.  If
       no date is input, the default result will be the earliest expiring
       option chain from the current date.
    
       @param: ticker
       @param: date"""
    ...

def get_calls(ticker, date=...): # -> DataFrame:
    """Extracts call option table for input ticker and expiration date
    
       @param: ticker
       @param: date"""
    ...

def get_puts(ticker, date=...): # -> DataFrame:
    """Extracts put option table for input ticker and expiration date
    
       @param: ticker
       @param: date"""
    ...

def get_expiration_dates(ticker): # -> list[Any]:
    """Scrapes the expiration dates from each option chain for input ticker
    
       @param: ticker"""
    ...

